## ctk: description Set up a dialog to explore structures.
## ctk: title File Explorer
## ctk: application '' ''
## ctk: strict  0
## ctk: code  0
## ctk: testCode  1
## ctk: subroutineName thisDialog
## ctk: autoExtractVariables  1
## ctk: autoExtract2Local  1
## ctk: modal 0
## ctk: buttons 
## ctk: isolGeom 0
## ctk: version 4.23
## ctk: onDeleteWindow  sub{exit}
## ctk: Toplevel  1
## ctk: argList  
## ctk: treewalk D 
## ctk: 2017 10 10 - 09:18:11

## ctk: uselib start

## ctk: uselib end

use Tk;
use Tk::Frame;
use Tk::Label;
use Tk::Listbox;
use Tk::Menu;
use Tk::Menubutton;
 $mw=MainWindow->new(-title=>'File Explorer');
## ctk: Globalvars
## ctk: Globalvars end
&main::init();
&main::thisDialog($mw);
MainLoop;

sub thisDialog {
my $hwnd = shift;
my %args =();
my $rv;
##
## ctk: Localvars
## ctk: Localvars end
##
my $mw = $hwnd->Toplevel();
$mw->configure(-title=> (exists $args{-title})? $args{-title}:'');
$mw->protocol('WM_DELETE_WINDOW',sub{exit});


## ctk: code generated by ctk_w version '4.23' 
## ctk: instantiate and display widgets 

## ctk: widgets generated using treewalk D
$w_Frame_001 = $mw -> Frame ( -relief , 'flat' , -background , '#ffffff' , -label , 'w_Frame_001'  ) -> pack(-anchor=>'nw', -fill=>'x', -side=>'top', -expand=>1);

$w_Menubutton_010 = $w_Frame_001 -> Menubutton ( -relief , 'flat' , -text , 'w_Menubutton_010' , -justify , 'left' , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'left');

$w_Menu_011 = $w_Menubutton_010 -> Menu (  ); $w_Menubutton_010->configure(-menu=>$w_Menu_011);

$w_command_012 = $w_Menu_011 -> command ( -label , 'w_command_012'  );

$w_Menubutton_013 = $w_Frame_001 -> Menubutton ( -relief , 'flat' , -text , 'w_Menubutton_013' , -justify , 'left' , -state , 'normal'  ) -> pack(-side=>'right', -anchor=>'ne');

$w_Menu_014 = $w_Menubutton_013 -> Menu (  ); $w_Menubutton_013->configure(-menu=>$w_Menu_014);

$w_command_015 = $w_Menu_014 -> command ( -label , 'w_command_015'  );

$wr_017 = $mw -> Frame ( -borderwidth , 2 , -relief , 'solid'  ) -> pack(-side=>'top', -expand=>1, -anchor=>'nw', -fill=>'x');

$wr_024 = $wr_017 -> Scrolled ( 'Listbox' , -background , '#ffffff' , -selectmode , 'single' , -relief , 'flat' , -scrollbars , 'se'  ) -> pack(-fill=>'both', -anchor=>'nw', -expand=>1, -side=>'left');
## ctk: order start  wr_024
$wr_024 -> configure(); $wr_016 = $wr_024 -> packAdjust ( -side , 'left'  );
## ctk: order end

$wr_015 = $wr_017 -> Scrolled ( 'ROText' , -state , 'normal' , -relief , 'sunken' , -scrollbars , 'se' , -wrap , 'none'  ) -> pack(-expand=>1, -side=>'left', -fill=>'both', -anchor=>'nw');

$w_Frame_007 = $mw -> Frame ( -relief , 'raised' , -label , 'w_Frame_007'  ) -> pack(-expand=>1, -side=>'bottom', -fill=>'x', -anchor=>'sw');

$w_Label_016 = $w_Frame_007 -> Label ( -relief , 'ridge' , -background , '#ffffff' , -text , 'Statusbar 1' , -justify , 'left'  ) -> pack(-anchor=>'nw', -fill=>'x', -side=>'left', -expand=>1);

## ctk: end of gened Tk-code

$rv = $mw;

 return $rv;

} ## end of thisDialog 

## ctk: end of dialog code
## ctk: callbacks
sub init { 1 }
## ctk: other code
## ctk: eof 2017 10 10 - 09:18:11
1;	## make perl compiler happy...

