#ifndef __GENERIC_CONFIG_H__
#define __GENERIC_CONFIG_H__
#undef GTK_VERSION
#define GTK_VERSION "2.24.28"
#undef HAVE_BZERO
#define HAVE_BZERO 1
#undef HAVE_FONTCONFIG_FONTCONFIG_H
#define HAVE_FONTCONFIG_FONTCONFIG_H 1
#undef HAVE_FREETYPE_FREETYPE_H
#define HAVE_FREETYPE_FREETYPE_H 1
#undef HAVE_ICONV_H
#define HAVE_ICONV_H 1
#undef HAVE_INT16_T
#define HAVE_INT16_T 1
#undef HAVE_INT32_T
#define HAVE_INT32_T 1
#undef HAVE_INT64_T
#define HAVE_INT64_T 1
#undef HAVE_INT8_T
#define HAVE_INT8_T 1
#undef HAVE_IO_H
#undef HAVE_REALLOCF
#undef HAVE_SNPRINTF
#define HAVE_SNPRINTF 1
#undef HAVE_SSIZE_T
#define HAVE_SSIZE_T 1
#undef HAVE_STDINT_H
#define HAVE_STDINT_H 1
#undef HAVE_STDIO_H
#define HAVE_STDIO_H 1
#undef HAVE_STDLIB_H
#define HAVE_STDLIB_H 1
#undef HAVE_STRCASECMP
#define HAVE_STRCASECMP 1
#undef HAVE_STRCASESTR
#undef HAVE_STRICMP
#undef HAVE_STRINGS_H
#define HAVE_STRINGS_H 1
#undef HAVE_STRING_H
#define HAVE_STRING_H 1
#undef HAVE_STRNCASECMP
#define HAVE_STRNCASECMP 1
#undef HAVE_STRNICMP
#undef HAVE_SYS_BITYPES_H
#define HAVE_SYS_BITYPES_H 1
#undef HAVE_SYS_INTTYPES_H
#undef HAVE_SYS_IPC_H
#define HAVE_SYS_IPC_H 1
#undef HAVE_SYS_SHM_H
#define HAVE_SYS_SHM_H 1
#undef HAVE_SYS_TYPES_H
#define HAVE_SYS_TYPES_H 1
#undef HAVE_UINT16_T
#define HAVE_UINT16_T 1
#undef HAVE_UINT32_T
#define HAVE_UINT32_T 1
#undef HAVE_UINT64_T
#define HAVE_UINT64_T 1
#undef HAVE_UINT8_T
#define HAVE_UINT8_T 1
#undef HAVE_UNISTD_H
#define HAVE_UNISTD_H 1
#undef HAVE_U_INT16_T
#define HAVE_U_INT16_T 1
#undef HAVE_U_INT32_T
#define HAVE_U_INT32_T 1
#undef HAVE_U_INT64_T
#define HAVE_U_INT64_T 1
#undef HAVE_U_INT8_T
#define HAVE_U_INT8_T 1
#undef HAVE_X11_EXTENSIONS_SHAPE_H
#define HAVE_X11_EXTENSIONS_SHAPE_H 1
#undef HAVE_X11_EXTENSIONS_XRANDR_H
#define HAVE_X11_EXTENSIONS_XRANDR_H 1
#undef HAVE_X11_EXTENSIONS_XRENDER_H
#define HAVE_X11_EXTENSIONS_XRENDER_H 1
#undef HAVE_X11_EXTENSIONS_XSHM_H
#define HAVE_X11_EXTENSIONS_XSHM_H 1
#undef HAVE_X11_XFT_XFT_H
#define HAVE_X11_XFT_XFT_H 1
#undef HAVE__SNPRINTF
#undef PERL_PATCHLEVEL
#define PERL_PATCHLEVEL 18
#undef PERL_POLLUTE
#define PERL_POLLUTE 1
#undef PERL_SUBVERSION
#define PERL_SUBVERSION 4
#undef PRIMA_CORE
#define PRIMA_CORE 1
#undef PRIMA_PLATFORM_X11
#define PRIMA_PLATFORM_X11 1
#undef PRIMA_SUBVERSION
#define PRIMA_SUBVERSION 45
#undef PRIMA_VERSION
#define PRIMA_VERSION 1
#undef WITH_GTK2
#define WITH_GTK2 1
#undef __INLINE__
#define __INLINE__ inline
#endif
