--- #YAML:1.0
name:                Convert-Temperature
version:             0.03
abstract:            ~
license:             ~
author:              
    - Filipe Dutra <mopy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
