#!/usr/bin/env perl
require 5.008;
use warnings;
use strict;
use File::Basename;

my $whoami = basename($0);

my $os = undef;
my $cpu = undef;
my $toolset = undef;
while (@ARGV)
{
    my $arg = shift(@ARGV);
    if ($arg eq '--native-data')
    {
	die "invalid invocation of list_platforms" unless @ARGV >= 3;
	$os = shift(@ARGV);
	$cpu = shift(@ARGV);
	$toolset = shift(@ARGV);
    }
}

# Exercise passing of --native-data to list_platforms
print "native-compiler c1\n";
print "platform $os.$cpu.$toolset.c2 -type native\n";
