#!perl

##################
#
# This file was automatically generated by ZooZ.pl v1.2
# on Thu Oct  5 16:29:01 2017.
# Project: Project 1
# File:    
#
##################

#
# Headers
#
use strict;
use warnings;

use Tk 804;

#
# Global variables
#
my (
     # MainWindow
     $MW,

     # Hash of all widgets
     %ZWIDGETS,
    );

#
# User-defined variables (if any)
#

######################
#
# Create the MainWindow
#
######################

$MW = MainWindow->new;

######################
#
# Load any images and fonts
#
######################
ZloadImages();
ZloadFonts ();



# Widget Label1 isa Label
$ZWIDGETS{'Label1'} = $MW->Label(
   -text => 'Label1',
  )->grid(
   -row    => 0,
   -column => 0,
  );

# Widget Label2 isa Label
$ZWIDGETS{'Label2'} = $MW->Label(
   -text => 'Label2',
  )->grid(
   -row    => 1,
   -column => 0,
  );

# Widget Button1 isa Button
$ZWIDGETS{'Button1'} = $MW->Button(
   -text => 'Button1',
  )->grid(
   -row    => 0,
   -column => 1,
  );

# Widget Entry1 isa Entry
$ZWIDGETS{'Entry1'} = $MW->Entry()->grid(
   -row    => 1,
   -column => 1,
  );

# Widget Button2 isa Button
$ZWIDGETS{'Button2'} = $MW->Button(
   -text => 'Button2',
  )->grid(
   -row    => 0,
   -column => 2,
  );

# Widget Button3 isa Button
$ZWIDGETS{'Button3'} = $MW->Button(
   -text => 'Button3',
  )->grid(
   -row    => 1,
   -column => 2,
  );

# Widget Button4 isa Button
$ZWIDGETS{'Button4'} = $MW->Button(
   -text => 'Button4',
  )->grid(
   -row    => 1,
   -column => 3,
  );

###############
#
# MainLoop
#
###############

MainLoop;

#######################
#
# Subroutines
#
#######################

sub ZloadImages {
}

sub ZloadFonts {
}

