#!C:\Perl\bin\perl.exe
## ctk: description 
## ctk: title 
## ctk: application 'test_import_export' 'c:/Dokumente und Einstellungen/marco/Projekte/ClickTk/test'
## ctk: strict  0
## ctk: code  1
## ctk: subroutineName thisDialog
## ctk: autoExtractVariables  1
## ctk: autoExtract2Local  1
## ctk: modal 0
## ctk: isolGeom 0
## ctk: version 3.097
## ctk: onDeleteWindow  sub{1}
## ctk: Toplevel  1
## ctk: argList -title , '???'     
## ctk: 2007 02 08 - 19:31:56

## ctk: uselib start

use lib 'c:/Dokumente und Einstellungen/marco/Projekte/ClickTk/test';

## ctk: uselib end

use Tk;
use Tk::Frame;
use Tk::Label;
use Tk::Listbox;
use Tk::TextEdit;
 $mw=MainWindow->new(-title=>'');
## ctk: Globalvars
## ctk: Globalvars end
&main::init();



## ctk: code generated by ctk_w version '3.097' 
## ctk: instantiate and display widgets 

$wr_001 = $mw -> Frame ( -relief , 'solid' , -borderwidth , 2  ) -> pack (-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_002 = $mw -> Frame ( -relief , 'solid' , -borderwidth , 2  ) -> pack (-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_004 = $wr_001 -> Listbox ( -background , '#ffffff' , -selectmode , 'single' , -relief , 'sunken'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'both', -expand=>1, -padx=>5);


$wr_005 = $wr_002 -> TextEdit ( -wrap , 'none' , -bg , '#ffffff' , -state , 'normal'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'both', -expand=>1, -padx=>5);


$wr_006 = $wr_002 -> Label ( -anchor , 'nw' , -background , '#0080ff' , -justify , 'left' , -text , 'Object name' , -relief , 'flat'  ) -> pack(-side=>'bottom', -anchor=>'sw', -fill=>'x', -expand=>1);


$wr_008 = $wr_001 -> Label ( -anchor , 'nw' , -background , '#80ffff' , -justify , 'left' , -text , 'Selection' , -relief , 'flat'  ) -> pack(-side=>'bottom', -anchor=>'sw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


## ctk: end of gened Tk-code


MainLoop;

## ctk: callbacks
sub init { 1 }
## ctk: other code
## ctk: eof 2007 02 08 - 19:31:56
1;	## make perl compiler happy...

