## ctk: description Enter parameter for new sheet
## ctk: title New spreadsheet
## ctk: application 'Hours' 'c:/Dokumente und Einstellungen/marco/Utilities/ClickTk/test/demo/hours'
## ctk: strict  0
## ctk: code  0
## ctk: subroutineName newSheet
## ctk: autoExtractVariables  1
## ctk: autoExtract2Local  0
## ctk: modal 1
## ctk: isolGeom 0
## ctk: version 3.095
## ctk: onDeleteWindow  sub{1}
## ctk: Toplevel  1
## ctk: 2006 12 02 - 18:48:18

use Tk;
use Tk::Entry;
use Tk::Frame;
use Tk::Label;
sub newSheet {
my $hwnd = shift;
my (%args) = @_;
my $rv;
##
## ctk: Localvars
## ctk: Localvars end
##
my $mw = $hwnd->DialogBox(
	-title=> (exists $args{-title})? $args{-title}:'New spreadsheet',
	 -buttons=> (exists $args{-buttons}) ? $args{-buttons} : ['OK','Cancel']);
$mw->protocol('WM_DELETE_WINDOW',sub{1});


## ctk: code generated by ctk_w version '3.095' 
## ctk: instantiate and display widgets 

$wr_001 = $mw -> Frame ( -relief , 'solid'  ) -> pack(-side=>'top', -anchor=>'nw', -fill=>'both', -expand=>1);


$wr_002 = $wr_001 -> Frame ( -borderwidth , 1 , -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_004 = $wr_002 -> Label ( -justify , 'left' , -text , 'File name' , -relief , 'flat'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_006 = $wr_002 -> Label ( -justify , 'left' , -text , 'Month' , -relief , 'flat'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_005 = $wr_002 -> Label ( -justify , 'left' , -text , 'Year' , -relief , 'flat'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_003 = $wr_001 -> Frame ( -borderwidth , 1 , -relief , 'solid'  ) -> pack(-side=>'left', -anchor=>'nw', -fill=>'both', -expand=>1);


$wr_007 = $wr_003 -> Entry ( -background , '#ffffff' , -justify , 'left' , -relief , 'sunken' , -textvariable , \$fName , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_008 = $wr_003 -> Entry ( -background , '#ffffff' , -justify , 'left' , -relief , 'sunken' , -textvariable , \$month , -state , 'normal'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_009 = $wr_003 -> Entry ( -background , '#ffffff' , -justify , 'left' , -relief , 'sunken' , -textvariable , \$year , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


## ctk: end of gened Tk-code

$rv =  $mw->Show();

 return $rv;

} ## end of newSheet 

## ctk: end of dialog code
## ctk: callbacks
## ctk: other code
## ctk: eof 2006 12 02 - 18:48:18
1;	## make perl compiler happy...

