## ctk: description Enter dayly hours
## ctk: title Dayly hours
## ctk: application 'Hours' 'c:/Dokumente und Einstellungen/marco/Utilities/ClickTk/test/demo/hours'
## ctk: strict  0
## ctk: code  0
## ctk: subroutineName enterHours
## ctk: autoExtractVariables  0
## ctk: autoExtract2Local  0
## ctk: modalDialogClassName DialogBox
## ctk: modal 1
## ctk: isolGeom 0
## ctk: version 3.099
## ctk: onDeleteWindow  sub{1}
## ctk: Toplevel  0
## ctk: argList -title , '???'   
## ctk: 2007 11 07 - 17:51:15

use Tk;
use Tk::Button;
use Tk::Entry;
use Tk::Frame;
use Tk::LabFrame;
use Tk::Label;
use Tk::Listbox;
sub enterHours {
my $hwnd = shift;
my (%args) = @_;
my $rv;
##
## ctk: Localvars
## ctk: Localvars end
##
my $mw = $hwnd->DialogBox(
	-title=> (exists $args{-title})? $args{-title}:'Dayly hours',
	 -buttons=> (exists $args{-buttons}) ? $args{-buttons} : ['OK','Cancel']);
$mw->protocol('WM_DELETE_WINDOW',sub{1});


## ctk: code generated by ctk_w version '3.099' 
## ctk: instantiate and display widgets 

$wr_001 = $mw -> Frame ( -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_002 = $mw -> Frame ( -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_003 = $wr_001 -> Listbox ( -background , '#ffffff' , -selectmode , 'single' , -relief , 'sunken'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'both', -expand=>1, -padx=>5);


$wr_004 = $wr_002 -> LabFrame ( -label , '1. Morning' , -labelside , 'acrosstop'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'both', -expand=>1);


$wr_006 = $wr_002 -> LabFrame ( -label , '2. Afternoon' , -relief , 'ridge' , -labelside , 'acrosstop'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'both', -expand=>1);


$wr_030 = $wr_002 -> Frame ( -borderwidth , 1 , -relief , 'solid'  ) -> pack(-side=>'top', -anchor=>'nw', -fill=>'both', -expand=>1);


$wr_007 = $wr_004 -> Frame ( -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_008 = $wr_004 -> Frame ( -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_032 = $wr_030 -> Button ( -background , '#ffffff' , -state , 'normal' , -relief , 'raised' , -text , 'Select'  ) -> pack(-side=>'left', -anchor=>'nw', -fill=>'x', -expand=>1);


$wr_033 = $wr_030 -> Button ( -background , '#ffffff' , -state , 'normal' , -text , 'save' , -relief , 'raised'  ) -> pack(-side=>'left', -anchor=>'nw', -fill=>'x', -expand=>1);


$wr_009 = $wr_006 -> Frame ( -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_010 = $wr_006 -> Frame ( -relief , 'solid'  ) -> pack(-anchor=>'nw', -side=>'left', -fill=>'both', -expand=>1);


$wr_011 = $wr_007 -> Label ( -justify , 'left' , -text , 'From' , -relief , 'flat'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_012 = $wr_007 -> Label ( -justify , 'left' , -text , 'To' , -relief , 'flat'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_014 = $wr_008 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$from1 , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'x', -expand=>1);


$wr_015 = $wr_008 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$to1 , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'x', -expand=>1);


$wr_016 = $wr_008 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$project , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'x', -expand=>1);


$wr_017 = $wr_009 -> Label ( -justify , 'left' , -text , 'From' , -relief , 'flat'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_019 = $wr_009 -> Label ( -justify , 'left' , -text , 'To' , -relief , 'flat'  ) -> pack(-side=>'top', -anchor=>'nw', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_021 = $wr_009 -> Label ( -justify , 'left' , -text , 'Project' , -relief , 'flat'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_023 = $wr_010 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$from2 , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'x', -expand=>1);


$wr_026 = $wr_010 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$to2 , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'x', -expand=>1);


$wr_028 = $wr_010 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$project , -state , 'normal'  ) -> pack(-anchor=>'nw', -side=>'top', -fill=>'x', -expand=>1);


$wr_022 = $wr_007 -> Label ( -justify , 'left' , -text , 'Project' , -relief , 'flat'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_024 = $wr_007 -> Label ( -justify , 'left' , -text , 'To' , -relief , 'flat'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_027 = $wr_008 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$activity1 , -state , 'normal'  ) -> pack(-side=>'top', -anchor=>'nw', -fill=>'x', -expand=>1);


$wr_029 = $wr_009 -> Label ( -justify , 'left' , -text , 'Activities' , -relief , 'flat'  ) -> pack(-anchor=>'nw', -side=>'top', -pady=>5, -fill=>'x', -expand=>1, -padx=>5);


$wr_031 = $wr_010 -> Entry ( -justify , 'left' , -relief , 'sunken' , -textvariable , \$activity2 , -state , 'normal'  ) -> pack(-side=>'top', -anchor=>'nw', -fill=>'x', -expand=>1);


## ctk: end of gened Tk-code

$rv =  $mw->Show();

 return $rv;

} ## end of enterHours 

## ctk: end of dialog code
## ctk: callbacks
sub select {
	## TODO : copy data from the listbox into input variables.
}
sub save {
	## TODO : copy data from the input variables into the listbox.
}
## ctk: other code
## ctk: eof 2007 11 07 - 17:51:15
1;	## make perl compiler happy...

