#!/usr/bin/perl
use v5.010;
use Mojo::UserAgent;
use Mojo::DOM;
# Fine grained response handling (dies on connection errors)
my $ua  = Mojo::UserAgent->new;
# my $res = $ua->get('mojolicious.org/perldoc')->result;
# if    ($res->is_success)  { say $res->body }
# elsif ($res->is_error)    { say $res->message }
# elsif ($res->code == 301) { say $res->headers->location }
# else                      { say 'Whatever...' }

my $filename = 'report.txt';
open(my $fh, '>', $filename) or die "Could not open file '$filename' $!";
print $fh "My first report generated by perl\n";
#close $fh;
#print "done\n";

# Scrape the latest headlines from a news site
my $text = $ua->get('blogs.perl.org') ->result->dom->find('h2 > a')->map('text')->join("\n");
my $href =$ua->get('blogs.perl.org') ->result->dom->find('href')->map('text')->join("\n");

#say $ua->find('[href]')->map(attr => 'href')->join("\n");
 
say $href;
 my $title = $ua->get('blogs.perl.org')->result->dom->at('title')->text;
 say $fh $title;
 print $fh  "ARTICOLE: \n";
 say  $fh $text;
 close $fh;
 print "done\n";