-- MySQL dump 10.11
--
-- Host: localhost    Database: course
-- ------------------------------------------------------
-- Server version	5.0.77

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `template`
--

DROP TABLE IF EXISTS `template`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `template` (
  `template_id` int(15) NOT NULL auto_increment,
  `template_title` varchar(255) default NULL,
  `template_description` text,
  `template_creator` varchar(64) default NULL,
  `template_crdate` int(15) default NULL,
  PRIMARY KEY  (`template_id`)
) ENGINE=MyISAM AUTO_INCREMENT=39 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

--
-- Dumping data for table `template`
--
-- WHERE:  TRUE ORDER BY template_id

LOCK TABLES `template` WRITE;
/*!40000 ALTER TABLE `template` DISABLE KEYS */;
INSERT INTO `template` VALUES (33,'admin_header','<box html_head>\r\n\r\n<body>\r\n\r\n<!-- CONTENT div: Holds all site content except for the footer.  This is what causes the footer to stick to the bottom -->\r\n<div id=\"content\">\r\n\r\n<box Header>\r\n<box Navbar>\r\n\r\n\r\n  <!-- PAGE CONTENT BEGINS: This is where you would define the columns (number, width and alignment) -->\r\n  <div id=\"page\">\r\n\r\n    <!-- 25 percent width column, aligned to the left -->\r\n    <div class=\"width25 floatLeft leftColumn\">\r\n      <!-- Gives the gradient block -->\r\n      <div class=\"gradient\">\r\n          <box Admin_Nav>\r\n      </div>\r\n    </div>\r\n\r\n\r\n    <!-- 75 percent width column, aligned to the right -->\r\n    <div class=\"width75 floatRight\">\r\n      <!-- Gives the gradient block -->\r\n      <div class=\"gradient\">\r\n       <br /><p class=\"login\"> <script language=\"Javascript\">login_box();</script></p>\r\n\r\n\r\n     <!--GENERATED CONTENT BEGINS  -->\r\n\r\n','1',1292786412),(34,'admin_footer','    </div>\r\n\r\n    </div>\r\n\r\n  </div>\r\n\r\n</div>\r\n\r\n<!-- FOOTER: Site footer for links, copyright, etc. -->\r\n<div id=\"footer\">\r\n  <div id=\"width\">\r\n    <span class=\"floatLeft\">\r\n<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png\" /></a>.\r\n    </span>\r\n\r\n    <span class=\"floatRight\">\r\n    <span class=\"floatRight\">\r\n<p>Copyright 2012 Stephen Downes ~ \r\n\r\n		Contact: <a  href=\"mailto:stephen@mooc.ca\">stephen@mooc.ca</a><br />\r\nThis page generated by <a href=\"http://grsshopper.mooc.ca\">gRSShopper</a>.\r\nCSS design adapted from <a href=\"http://fullahead.org\" title=\"Goto Fullahead\">Fullahead</a>  </p>\r\n    </span>\r\n  </div>\r\n\r\n</div>\r\n\r\n</body>\r\n\r\n</html>\r\n\r\n\r\n<!--\r\n ____________________________________________________________\r\n|                                                            |\r\n|    DESIGN + Pat Heard { http://fullahead.org }             |\r\n|      DATE + 2006.03.19                                     |\r\n|    Extensively modified by Stephen Downes Feb 2010         |\r\n| COPYRIGHT + Free use if this notice is left in place       |\r\n|____________________________________________________________|\r\n\r\n-->\r\n','1',1292786526),(35,'page_header','<box html_head>\r\n\r\n<body>\r\n\r\n<!-- CONTENT div: Holds all site content except for the footer.  This is what causes the footer to stick to the bottom -->\r\n<div id=\"content\">\r\n\r\n<box Header>\r\n<box Navbar>\r\n\r\n\r\n  <!-- PAGE CONTENT BEGINS: This is where you would define the columns (number, width and alignment) -->\r\n  <div id=\"page\">\r\n\r\n    <!-- 25 percent width column, aligned to the left -->\r\n    <div class=\"width25 floatLeft leftColumn\">\r\n      <!-- Gives the gradient block -->\r\n      <div class=\"gradient\">\r\n          <box Sidebar>\r\n      </div>\r\n    </div>\r\n\r\n\r\n    <!-- 75 percent width column, aligned to the right -->\r\n    <div class=\"width75 floatRight\">\r\n      <!-- Gives the gradient block -->\r\n      <div class=\"gradient\">\r\n       <br /><p class=\"login\"> <script language=\"Javascript\">login_box();</script></p>\r\n\r\n\r\n     <!--GENERATED CONTENT BEGINS  -->','1',1292795461),(36,'page_footer','    </div>\r\n\r\n    </div>\r\n\r\n  </div>\r\n\r\n\r\n\r\n\r\n</div>\r\n\r\n<!-- FOOTER: Site footer for links, copyright, etc. -->\r\n<div id=\"footer\">\r\n  <div id=\"width\">\r\n    <span class=\"floatLeft\">\r\n<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png\" /></a>.\r\n    </span>\r\n\r\n    <span class=\"floatRight\">\r\n<p>Copyright 2012 Stephen Downes ~ \r\n\r\n		Contact: <a  href=\"mailto:stephen@mooc.ca\">stephen@mooc.ca</a><br />\r\nThis page generated by <a href=\"http://grsshopper.mooc.ca\">gRSShopper</a>. \r\nCSS design adapted from <a href=\"http://fullahead.org\" title=\"Goto Fullahead\">Fullahead</a> </p>\r\n    </span>\r\n  </div>\r\n\r\n</div>\r\n\r\n</body>\r\n\r\n</html>\r\n\r\n','1',1292795521),(37,'email_header','<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"DTD/xhtml1-transitional.dtd\">\r\n<html>\r\n<head>\r\n<title>The Daily ~ <st_name></title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<STYLE TYPE=\"text/css\">\r\n  a {color:#0000aa; }\r\n</STYLE>\r\n\r\n</head>\r\n\r\n<body style=\"background: #ffffff;\">\r\n<div style=\"border: 1px solid #85B4D1;  background: #ffffff;\">\r\n\r\n\r\n   <div style=\"background: #ffffff; margin:1em;\">\r\n   <p style=\"float:right;margin: 0; padding: 0; font: small-caps 100 12pt arial,sans-serif;\">\r\n   [<a style=\"text-decoration: none;color: #4989C5;\" href=\"<st_url>\" title=\"Home\">Home</a>]\r\n   [<a style=\"text-decoration: none;color: #4989C5;\" href=\"<st_url>about.htm\">About</a>]\r\n   [<a style=\"text-decoration: none;color: #4989C5;\" href=\"<st_url>contact.htm\" title=\"Contact\">Contact</a>]</p>\r\n\r\n<a href=\"<st_url>\"><img src=\"<st_url>images/grsshopper_flat.jpg\" alt=\"gRSShopper\" border=\"0\"/ title=\"gRSShopper\" alt=\"gRSShopper banner image\"></a>\r\n<hr>\r\n\r\n   </div>\r\n\r\n\r\n\r\n\r\n','1',1293583208),(38,'email_footer','<!-- FOOTER: Site footer for links, copyright, etc. -->\r\n   <div id=\"footer\">\r\n        <br /><hr>\r\n<p  style=\"font: 400 0.8em verdana, arial, sans-serif;  line-height: 150%;\">This newsletter is sent only at the request of subscribers. If you would like to unsubscribe,\r\n<a href=\"<st_cgi>login.cgi?action=Unsub&pid=PERSON&sid=SUBSCRIBER\">Click here</a>.</p>\r\n\r\n\r\n\r\n\r\n<p  style=\"font: 400 0.8em verdana, arial, sans-serif;  line-height: 150%;\">Know a friend who might enjoy this newsletter? Feel free to forward this newsletter to your colleagues. If you received this issue from a friend and would like a free subscription of your own, \r\nyou can join our mailing list. <a href=\"<st_cgi>login.cgi?action=Register\">Click here to subscribe</a>.</p>\r\n\r\n        <div id=\"width\" style=\"margin-left:15px;\">\r\n         <span style=\"float:left;\">\r\n<p><a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png\" /></a>.</p>\r\n          </span>\r\n          <span style=\"float:right;\">\r\n<p>Copyright 2012 CCK12 ~ \r\n		Contact: <a  href=\"mailto:stephen@mooc.ca\">stephen@mooc.ca</a><br />\r\nThis page generated by <a href=\"http://grsshopper.mooc.ca\">gRSShopper</a>. \r\nCSS design adapted from <a href=\"http://fullahead.org\" title=\"Goto Fullahead\">Fullahead</a> </p>\r\n         </span>\r\n\r\n \r\n\r\n\r\n     </div>\r\n\r\n</div>\r\n\r\n</body>\r\n\r\n</html>\r\n','1',1293583259);
/*!40000 ALTER TABLE `template` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2012-07-22 13:42:13
