<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<link rel="stylesheet" href="$themeDir/theme.css" type="text/css" />		
	<link rel="stylesheet" href="$themeDir/wiki.css" type="text/css" />
	<meta name="keywords" content="$utils.siteKeywords" />
	<meta name="description" content="$utils.siteDescription" />
	<title>$utils.siteTitle: $!blog.urlName</title>
	
	<link rel="alternate" type="application/rss+xml" title="$blog.urlName articles" href="$base/blogs/$blog.urlName/feeds/rss_2.0" />
	<link rel="alternate" type="application/atom+xml" title="$blog.urlName articles" href="$base/blogs/$blog.urlName/feeds/atom_0.3" />	
</head>


<body> 

<table cellpadding="0" cellspacing="0" height="100%" width="100%">

	<tr>
		<td height="100" colspan="2" style="border-bottom:  1px solid #000000; background: #123456">
			<a href="$base/blogs/$blog.urlName" style="font-size: 44px;font-weight: bold; text-decoration: none; color: #FFFFFF; margin-left: 7px; ">$!blog.fullName</a><br/>
			<span style="font-family: Geneva, Arial, Helvetica, sans-serif; font-size: 12px;color: #FFFFFF; margin-left: 7px;">
			$!blog.description
			</span>
		</td>
	</tr>
	
	<tr valign="top">
		<td valign="top">$content</td>
		<td width="230">
			<table border="0" cellpadding="0" cellspacing="0" 
					style="margin-left: 15px; padding-left: 5px; " width="100%" height="100%">
				<tr valign="top">
					<td align="left">

					#systemBox()
					#searchBox()
					#calendarBox()
					#recentEntriesBox()
					#recentCommentsBox()
					#archivesBox()
					#usersBox()
					#categoryBox()
					#linksBox()
					#feedsBox()				
					#visitedPagesBox()					
					#referersBox()

					
					</td>
				</tr>
			</table>
		</td>		
	</tr>

	<tr>
	<td colspan="2" style="border-top:  1px solid #000000; background: #123456" align="right">
	<span style="font-family: Geneva, Arial, Helvetica, sans-serif; font-size: 10px;color: #FFFFFF; padding-right: 5px;">
		Powered by <a href="http://blogunity.sf.net" style="color: #FFFFFF; font-size: 10px;">Blogunity</a> $utils.version ($utils.codename), build $utils.build
	</span>	
	</td>
	</tr>

</table>
</body>
</html>