#!perl
=pod
    This module is RUN: $perl convertor_gui.pl
    NEED Conver::Temperature.pm - is included
        and ZooZ.pl program create Gui and Tk::ToolBar

=cut
##################
#
# This file was automatically generated by ZooZ.pl v1.2
# on Fri Oct  6 08:35:07 2017.
# Project: Project 1
# File:    
#
##################

#
# Headers
#
use strict;
use warnings;
use Convert::Temperature;

use Tk 804;

#
# Global variables
#
my (
     # MainWindow
     $MW,

     # Hash of all widgets
     %ZWIDGETS,
    );
    
my $conv = new Convert::Temperature();

#
# User-defined variables (if any)
#

######################
#
# Create the MainWindow
#
######################

$MW = MainWindow->new;

######################
#
# Load any images and fonts
#
######################
ZloadImages();
ZloadFonts ();



# Widget Label1 isa Label
$ZWIDGETS{'Label1'} = $MW->Label(
   -takefocus => 0,
   -text      => 'Fahrenheit',
  )->grid(
   -row    => 0,
   -column => 0,
  );

# Widget Label2 isa Label
$ZWIDGETS{'Label2'} = $MW->Label(
   -takefocus => 0,
   -text      => 'Celsius',
  )->grid(
   -row    => 1,
   -column => 0,
  );

# Widget Entry1 isa Entry
$ZWIDGETS{'Entry1'} = $MW->Entry(
   -exportselection => 1,
   -takefocus       => 1,
  )->grid(
   -row    => 0,
   -column => 1,
  );

# Widget Entry2 isa Entry
$ZWIDGETS{'Entry2'} = $MW->Entry()->grid(
   -row    => 1,
   -column => 1,
  );

# Widget Button1 isa Button
$ZWIDGETS{'Button1'} = $MW->Button(
   -text => 'Calculeaza',
   -command => \&calculeaza,
  )->grid(
   -row    => 0,
   -column => 2,
  );

# Widget Button2 isa Button
$ZWIDGETS{'Button2'} = $MW->Button(
   -text => 'Close',
   -command => \&exit,
  )->grid(
   -row    => 1,
   -column => 2,
  );

# Widget Button2 isa Button
$ZWIDGETS{'Button3'} = $MW->Button(
   -text => 'Clear',
   -command => \&clear,
  )->grid(
   -row    => 2,
   -column => 2,
  );
###############
#
# MainLoop
#
###############

MainLoop;

#######################
#
# Subroutines
#
#######################

sub ZloadImages {
}

sub ZloadFonts {
}

sub main::clear {
    $ZWIDGETS{'Entry1'}->delete(0,'end');
    $ZWIDGETS{'Entry2'}->delete(0,'end');
}

sub close {
	exit;
}

sub calculeaza {
    my $fahr = $ZWIDGETS{'Entry1'}-> get();
    #print "$fahr";
    my $cels = $conv->from_fahr_to_cel($fahr);  # result in Celsius
    $ZWIDGETS{'Entry2'}->insert('end', $cels);
}

